spring.application.name=spring-security-demo
# Application configuration
server.port=8081

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging configuration
logging.level.org.springframework.security=DEBUG
logging.level.ma.fstg.security=DEBUG